### ISSUE TITLE
FCGF -PCL Model Weights

### ISSUE THREAD

**Issue by yuvalH9** [liuQuan98/GCL#5]
Hi @liuQuan98 ,

Can you please release the weights for the FCGF-PCL model?

Thanks,
Yuval

**Comment by liuQuan98** [comment]
Hi @yuvalH9 ,

The weights are posted [here](https://drive.google.com/file/d/1IgJCzvZrbAVuetlOP7--xW_fDV5c3MyB/view?usp=sharing).

Best,
Quan Liu

**Comment by yuvalH9** [comment]
@liuQuan98 thanks!

Can you also release the weights for the other PCL methods you trained for Table 1?

Yuval

**Comment by liuQuan98** [comment]
> @liuQuan98 thanks!
> 
> Can you also release the weights for the other PCL methods you trained for Table 1?
> 
> Yuval

Reproducing full Table1 also requires the dataset code, test code and everything else necessary. I have quite some workload these days, and the way I test these methods involve a lot of workarounds that works better than their looks. I will probably clean up all those mess for result reproduction in the near future.

FYI, you can produce the results by yourself if you really need them. You can train and test Predator on my dataset using the APR code repo by disabling the reconstruction part of the trainer. I believe this is the fastest workaround for Predator. On the other hand, SpinNet, D3Feat and Geotransformer performance are reported using the **official weights of the original paper** instead of those trained by me (SpinNet didn't release the training procedure so re-training is impossible; D3Feat and GeoTransformer trained using the two-stage strategy perform worse than the official model and I do not see any meaning in releasing the 'diverged' model weights). CofiNet on the other hand reaches decent performance using my datasets. All you need to do is simply accommodating `complement_data_loader.py` to other code repos.
